const ready=()=>window.FinanceApp?Promise.resolve():new Promise(r=>window.addEventListener('finance:ready',r,{once:true}));
await ready();
const A=window.FinanceApp,{S,user,write,secureRequest,fmt,readMoney,formatMoneyInput,esc,sheet,hide,toast,$}=A;
let catalog=[],selected=null,pendingDelete=null,lastQuoteSignature='';
const rub=n=>fmt(Number(n||0),'RUB');
const positionValue=p=>Number(p.quantity||0)*(Number(p.face_value||0)*Number(p.current_price_percent||0)/100+Number(p.accrued_interest||0));
const yieldText=p=>Number(p.yield_percent)>0?`${Number(p.yield_percent).toFixed(2)}%`:Number(p.coupon_percent)>0?`купон ${Number(p.coupon_percent).toFixed(2)}%`:/^SU290/.test(String(p.secid||''))?'плавающий купон':'нет расчёта';
function render(){const list=$('#ofz-list'),total=(S.ofz||[]).reduce((s,p)=>s+positionValue(p),0);$('#ofz-summary').textContent=rub(total);if(!list)return;list.innerHTML=(S.ofz||[]).length?(S.ofz||[]).map(p=>{const value=positionValue(p),cost=Number(p.invested_amount||0),profit=value-cost;return`<article class="ofz-card"><div class="ofz-card-head"><div><h3>${esc(p.short_name||p.secid)}</h3><span>${esc(p.secid)} · ${Number(p.quantity||0)} шт.</span></div><b class="ofz-yield">${yieldText(p)}</b></div><div class="ofz-card-values"><div><span>Текущая стоимость</span><strong>${rub(value)}</strong></div><div><span>Результат по цене</span><strong class="${profit>=0?'positive':'negative'}">${profit>=0?'+':''}${rub(profit)}</strong></div></div><div class="ofz-card-foot"><span>Купон ${rub(p.coupon_value)} · ${p.next_coupon_date?new Date(p.next_coupon_date).toLocaleDateString('ru-RU'):'дата уточняется'}</span><span>Погашение ${p.maturity_date?new Date(p.maturity_date).toLocaleDateString('ru-RU'):'—'}</span></div><div class="ofz-card-actions"><button data-delete-ofz="${p.id}">${pendingDelete===p.id?'Подтвердить удаление':'Удалить ОФЗ'}</button></div></article>`}).join(''):'<div class="empty-state">Добавьте ОФЗ — цена, купон и погашение подставятся автоматически</div>'}
function fillCatalog(){const select=$('#ofz-security');select.innerHTML='<option value="">Выберите выпуск</option>'+catalog.map(x=>`<option value="${esc(x.secid)}">${esc(x.short_name)} · погашение ${x.maturity_date?new Date(x.maturity_date).toLocaleDateString('ru-RU'): '—'}</option>`).join('');$('#ofz-market-status').textContent=`Доступно выпусков: ${catalog.length} · MOEX`}
function calculate(){selected=catalog.find(x=>x.secid===$('#ofz-security').value)||null;const preview=$('#ofz-preview'),amount=readMoney($('#ofz-amount').value);if(!selected){preview.hidden=true;$('#ofz-calculation').textContent='Выберите выпуск и укажите сумму';return}preview.hidden=false;preview.innerHTML=`<strong>${esc(selected.full_name||selected.short_name)}</strong><span>${esc(selected.secid)}</span><div class="ofz-preview-grid"><div><span>Цена</span><strong>${Number(selected.price_percent).toFixed(3)}%</strong></div><div><span>Доходность / купон</span><strong>${yieldText(selected)}</strong></div><div><span>Купон</span><strong>${rub(selected.coupon_value)}</strong></div><div><span>Следующий купон</span><strong>${selected.next_coupon_date?new Date(selected.next_coupon_date).toLocaleDateString('ru-RU'):'—'}</strong></div></div>`;const one=Number(selected.face_value)*Number(selected.price_percent)/100+Number(selected.accrued_interest||0),qty=Math.floor(amount/one),spent=qty*one;$('#ofz-calculation').innerHTML=qty>0?`Будет добавлено <b>${qty} шт.</b><br>Расчётная стоимость ${rub(spent)} с НКД · остаток ${rub(amount-spent)}`:`На одну бумагу с НКД нужно примерно ${rub(one)}`}
async function loadCatalog(force=false){try{const data=await secureRequest({action:'ofz_catalog',force});catalog=data.items||[];fillCatalog()}catch(e){console.error(e);$('#ofz-market-status').textContent='Не удалось загрузить MOEX';toast('Котировки ОФЗ временно недоступны')}}
async function refreshPositions(){if(!(S.ofz||[]).length)return;try{const data=await secureRequest({action:'ofz_quotes',secids:S.ofz.map(x=>x.secid)});for(const q of data.items||[]){const p=S.ofz.find(x=>x.secid===q.secid);if(p)Object.assign(p,{current_price_percent:q.price_percent,accrued_interest:q.accrued_interest,coupon_value:q.coupon_value,coupon_percent:q.coupon_percent,next_coupon_date:q.next_coupon_date,maturity_date:q.maturity_date,yield_percent:q.yield_percent,quote_updated_at:new Date().toISOString()})}render();A.render()}catch(e){console.error(e)}}
async function save(e){e.preventDefault();if(!selected)return toast('Выберите выпуск ОФЗ');const amount=readMoney($('#ofz-amount').value),one=Number(selected.face_value)*Number(selected.price_percent)/100+Number(selected.accrued_interest||0),quantity=Math.floor(amount/one);if(quantity<1)return toast(`Минимальная сумма около ${rub(one)}`);const button=e.target.querySelector('[type="submit"]');button.disabled=true;button.textContent='Добавляю…';try{const body={telegram_id:user.id,secid:selected.secid,short_name:selected.short_name,full_name:selected.full_name,quantity,invested_amount:quantity*one,purchase_price_percent:selected.price_percent,current_price_percent:selected.price_percent,face_value:selected.face_value,face_currency:selected.face_currency||'RUB',accrued_interest:selected.accrued_interest||0,coupon_value:selected.coupon_value||0,coupon_percent:selected.coupon_percent,maturity_date:selected.maturity_date,next_coupon_date:selected.next_coupon_date,yield_percent:selected.yield_percent,broker:$('#ofz-broker').value.trim()||null,purchase_date:$('#ofz-purchase-date').value};const rows=await write('ofz_positions',{body});S.ofz.unshift(rows[0]);hide('ofz-sheet');e.target.reset();selected=null;render();A.render();toast(`Добавлено: ${quantity} шт. ${body.short_name}`)}catch(err){console.error(err);toast('Не удалось добавить ОФЗ')}finally{button.disabled=false;button.textContent='Добавить ОФЗ'}}
async function remove(id){if(pendingDelete!==id){pendingDelete=id;render();return toast('Нажмите ещё раз для удаления')}const old=[...S.ofz];S.ofz=S.ofz.filter(x=>x.id!==id);pendingDelete=null;render();A.render();try{await write('ofz_positions',{method:'DELETE',query:`id=eq.${id}`});toast('ОФЗ удалена')}catch(e){S.ofz=old;render();A.render();toast('Не удалось удалить ОФЗ')}}
$('#add-ofz').onclick=()=>{sheet('ofz-sheet');$('#ofz-purchase-date').value=new Date().toISOString().slice(0,10);if(!catalog.length)loadCatalog()};$('#ofz-security').onchange=calculate;$('#ofz-amount').oninput=e=>{formatMoneyInput(e.target);calculate()};$('#ofz-form').onsubmit=save;document.addEventListener('click',e=>{const b=e.target.closest('[data-delete-ofz]');if(b)remove(b.dataset.deleteOfz)});window.addEventListener('finance:render',()=>{render();const signature=(S.ofz||[]).map(x=>x.secid).sort().join(',');if(signature&&signature!==lastQuoteSignature){lastQuoteSignature=signature;refreshPositions()}});render();loadCatalog();
