const ready=()=>window.FinanceApp?Promise.resolve():new Promise(r=>window.addEventListener('finance:ready',r,{once:true}));
await ready();
const A=window.FinanceApp,{S,user,tg,write,load,fmt,conv,toRub,esc,date,sheet,hide,toast,$,$$}=A;
let importRows=[];
const accountCurrency=id=>S.accounts.find(a=>a.id===id)?.currency||'RUB';
const assetUnitPrice=a=>{if(a.valuation_mode==='live'&&S.rates){const symbol=(a.symbol||'').toUpperCase(),coin={BTC:'bitcoin',ETH:'ethereum',USDT:'tether',TRX:'tron'}[symbol];if(coin&&S.rates.crypto[coin])return a.currency==='RUB'?S.rates.crypto[coin].rub:S.rates.crypto[coin].usd}return Number(a.current_price||0)};
const assetValue=a=>Number(a.quantity||0)*assetUnitPrice(a);

function renderDebts(){const open=S.debts.filter(d=>!d.is_settled),mine=open.filter(d=>d.direction==='owed_to_me').reduce((s,d)=>s+conv(d.amount,d.currency),0),owed=open.filter(d=>d.direction==='i_owe').reduce((s,d)=>s+conv(d.amount,d.currency),0);$('#debts-total').textContent=open.length?`Мне ${fmt(mine)} · Я ${fmt(owed)}`:'Нет открытых долгов';$('#debts-list').innerHTML=open.length?open.map(d=>`<article class="suite-row"><div><strong>${esc(d.person)}</strong><span>${d.direction==='owed_to_me'?'Должен вам':'Вы должны'}${d.due_date?` · до ${date(d.due_date)}`:''}</span>${d.note?`<small>${esc(d.note)}</small>`:''}</div><div class="suite-value ${d.direction==='owed_to_me'?'positive':'negative'}"><strong>${fmt(d.amount,d.currency)}</strong><button data-settle-debt="${d.id}">Закрыть</button></div></article>`).join(''):'<div class="empty-state">Открытых долгов нет</div>'}
function renderAssets(){const total=S.assets.reduce((s,a)=>s+conv(assetValue(a),a.currency),0);$('#tracked-assets-total').textContent=fmt(total);$('#assets-list').innerHTML=S.assets.length?S.assets.map(a=>{const value=assetValue(a),cost=Number(a.quantity||0)*Number(a.purchase_price||0),profit=value-cost,pct=cost?profit/cost*100:0;return`<article class="suite-row"><div><strong>${esc(a.name)}</strong><span>${esc(a.asset_type)}${a.symbol?` · ${esc(a.symbol.toUpperCase())}`:''}${a.valuation_mode==='live'?' · live':''}</span><small>${a.quantity} × ${fmt(assetUnitPrice(a),a.currency)}</small></div><div class="suite-value"><strong>${fmt(value,a.currency)}</strong>${cost?`<span class="${profit>=0?'positive':'negative'}">${profit>=0?'+':''}${fmt(profit,a.currency)} · ${pct.toFixed(1)}%</span>`:''}<button data-delete-asset="${a.id}">Удалить</button></div></article>`}).join(''):'<div class="empty-state">Добавьте имущество, золото, акции или крипту</div>'}
function renderHealth(){const now=new Date(),since=new Date(now);since.setMonth(now.getMonth()-3);const recent=S.transactions.filter(t=>new Date(t.transaction_date)>=since),income=recent.filter(t=>t.type==='income').reduce((s,t)=>s+historicRub(t),0)/3,expense=recent.filter(t=>t.type==='expense').reduce((s,t)=>s+historicRub(t),0)/3,fixed=S.events.filter(e=>['rent','credit','subscription'].includes(e.event_type)).reduce((s,e)=>s+conv(e.amount,e.currency)*(e.recurrence==='yearly'?1/12:1),0),cash=S.accounts.reduce((s,a)=>s+conv(A.S.transactions.filter(t=>t.account_id===a.id).reduce((v,t)=>v+Number(t.amount)*(t.type==='income'?1:-1),Number(a.initial_balance||0)),a.currency),0)+S.deposits.reduce((s,d)=>s+conv(d.principal,d.currency),0),debt=S.debts.filter(d=>!d.is_settled&&d.direction==='i_owe').reduce((s,d)=>s+conv(d.amount,d.currency),0),runway=expense?cash/expense:0,saving=income?(income-expense)/income*100:0,fixedShare=income?fixed/income*100:0,debtShare=cash?debt/cash*100:0;let score=50+Math.min(runway,6)*5+Math.max(-20,Math.min(20,saving/2))-Math.min(20,fixedShare/4)-Math.min(20,debtShare/3);score=Math.round(Math.max(0,Math.min(100,score)));$('#score-value').textContent=score;$('#score-ring').style.setProperty('--score',`${score*3.6}deg`);$('#score-label').textContent=score>=80?'Отличная устойчивость':score>=60?'Хорошая форма':score>=40?'Нужен запас':'Высокий финансовый риск';$('#score-advice').textContent=runway<3?'Сначала доведите подушку хотя бы до 3 месяцев расходов.':fixedShare>50?'Снизьте долю обязательных платежей.':'Продолжайте сохранять положительную норму сбережений.';$('#runway-months').textContent=runway?runway.toFixed(1):'—';$('#fixed-share').textContent=`${fixedShare.toFixed(0)}%`;$('#debt-share').textContent=`${debtShare.toFixed(0)}%`;$('#saving-rate').textContent=`${saving.toFixed(0)}%`;$('#health-score').textContent=`${score}/100 · подушка ${runway.toFixed(1)} мес.`}
function historicRub(t){const c=t.currency||accountCurrency(t.account_id);return Number(t.amount||0)*Number(t.fx_rate_to_rub||toRub(c))}
function renderMerchant(){const box=$('#merchant-analytics');if(!box)return;const map={};S.transactions.filter(t=>t.type==='expense').forEach(t=>{const key=t.merchant||t.note||t.categories?.name||'Другое';map[key]=(map[key]||0)+historicRub(t)});S.transactions.filter(t=>t.is_refund).forEach(t=>{const original=S.transactions.find(x=>x.id===t.original_transaction_id),key=original?.merchant||t.merchant||original?.note||'Другое';map[key]=Math.max(0,(map[key]||0)-historicRub(t))});box.innerHTML=Object.entries(map).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`<div class="asset-row"><span>${esc(k)}</span><strong>${fmt(conv(v,'RUB'))}</strong></div>`).join('')||'<div class="empty-state">Добавьте merchant в операциях</div>'}
function renderRules(){setText('rules-count',S.rules.length?`${S.rules.length} правил`:'Автокатегоризация');$('#rules-list').innerHTML=S.rules.length?S.rules.map(r=>`<article class="suite-row"><div><strong>«${esc(r.pattern)}»</strong><span>→ ${esc(r.categories?.emoji||'')} ${esc(r.categories?.name||'Категория')}</span></div><div class="suite-value"><button data-delete-rule="${r.id}">Удалить</button></div></article>`).join(''):'<div class="empty-state">Правил пока нет</div>';$('#rule-category').innerHTML=S.categories.filter(c=>c.type==='expense').map(c=>`<option value="${c.id}">${esc(c.emoji||'')} ${esc(c.name)}</option>`).join('')}
function currentNetWorth(){const account=S.accounts.reduce((sum,a)=>{const v=S.transactions.reduce((n,t)=>{const amount=Number(t.amount||0);if(t.type==='transfer'){if(t.account_id===a.id)n-=amount;if(t.destination_account_id===a.id)n+=amount;return n}return t.account_id===a.id?n+amount*(t.type==='income'?1:-1):n},Number(a.initial_balance||0));return sum+conv(v,a.currency)},0),deposits=S.deposits.reduce((s,d)=>s+conv(d.principal,d.currency),0),assets=S.assets.reduce((s,a)=>s+conv(assetValue(a),a.currency),0),debts=S.debts.filter(d=>!d.is_settled&&d.direction==='i_owe').reduce((s,d)=>s+conv(d.amount,d.currency),0);return{account,deposits,assets,debts,total:account+deposits+assets-debts}}
function renderNetWorth(){const n=currentNetWorth();setText('net-worth-current',fmt(n.total));const months=[];for(let i=11;i>=0;i--){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-i);const key=d.toISOString().slice(0,7),rows=S.snapshots.filter(x=>x.snapshot_date.startsWith(key));months.push({label:d.toLocaleDateString('ru-RU',{month:'short'}),value:rows.length?Number(rows.at(-1).net_worth_rub):null})}const values=months.filter(x=>x.value!==null).map(x=>x.value),max=Math.max(...values,1),min=Math.min(...values,0);$('#net-worth-chart').innerHTML=values.length?months.map(x=>`<i class="net-worth-bar" title="${x.value===null?'Нет данных':fmt(x.value,'RUB')}" style="height:${x.value===null?3:Math.max(8,(x.value-min)/Math.max(1,max-min)*88+12)}%"><span>${x.label}</span></i>`).join(''):'<div class="empty-state">Первый снимок капитала будет сохранён сегодня</div>'}
async function saveTodaySnapshot(){if(!user||S.snapshotSaving)return;const today=new Date().toISOString().slice(0,10);if(S.snapshots.some(x=>x.snapshot_date===today))return;S.snapshotSaving=true;const n=currentNetWorth();try{const rows=await write('net_worth_snapshots',{query:'on_conflict=telegram_id,snapshot_date',body:{telegram_id:user.id,snapshot_date:today,accounts_rub:n.account,deposits_rub:n.deposits,assets_rub:n.assets,debts_rub:n.debts,net_worth_rub:n.total}});if(rows[0])S.snapshots.push(rows[0]);renderNetWorth()}catch(e){console.error(e)}finally{S.snapshotSaving=false}}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function renderAll(){renderDebts();renderAssets();renderHealth();renderMerchant();renderRules();renderNetWorth();saveTodaySnapshot()}
window.addEventListener('finance:render',renderAll);

async function saveDebt(e){e.preventDefault();const form=e.target,button=form.querySelector('[type="submit"]'),payload={telegram_id:user.id,person:$('#debt-person').value.trim(),direction:$('#debt-direction').value,amount:Number($('#debt-amount').value),currency:$('#debt-currency').value,due_date:$('#debt-due').value||null,note:$('#debt-note').value.trim()||null};if(!payload.person||!payload.amount)return toast('Заполните имя и сумму');button.disabled=true;button.textContent='Добавляю…';try{const rows=await write('debts',{body:payload});if(!rows[0])throw Error('Supabase не вернул созданный долг');S.debts.unshift(rows[0]);renderDebts();renderHealth();form.reset();toast('Долг добавлен')}catch(err){console.error(err);toast(`Не удалось добавить: ${String(err.message).slice(0,70)}`)}finally{button.disabled=false;button.textContent='Добавить долг'}}
async function saveAsset(e){e.preventDefault();const form=e.target,button=form.querySelector('[type="submit"]');button.disabled=true;button.textContent='Добавляю…';try{const rows=await write('assets',{body:{telegram_id:user.id,name:$('#asset-name').value.trim(),asset_type:$('#asset-type').value,symbol:$('#asset-symbol').value.trim().toUpperCase()||null,quantity:Number($('#asset-quantity').value),purchase_price:Number($('#asset-purchase').value)||null,current_price:Number($('#asset-price').value),currency:$('#asset-currency').value,valuation_mode:$('#asset-mode').value}});if(!rows[0])throw Error('Актив не создан');S.assets.unshift(rows[0]);renderAssets();renderHealth();renderNetWorth();form.reset();toast('Актив добавлен')}catch(err){console.error(err);toast('Не удалось добавить актив')}finally{button.disabled=false;button.textContent='Добавить актив'}}
document.addEventListener('click',e=>{const settle=e.target.closest('[data-settle-debt]'),del=e.target.closest('[data-delete-asset]');if(settle)settleDebt(settle.dataset.settleDebt);if(del)deleteAsset(del.dataset.deleteAsset)});
async function settleDebt(id){const debt=S.debts.find(d=>d.id===id);if(!debt)return;debt.is_settled=true;renderDebts();renderHealth();try{await write('debts',{method:'PATCH',query:`id=eq.${id}&telegram_id=eq.${user.id}`,body:{is_settled:true}});toast('Долг закрыт')}catch(err){debt.is_settled=false;renderDebts();renderHealth();toast('Не удалось закрыть долг')}}
async function deleteAsset(id){const index=S.assets.findIndex(a=>a.id===id);if(index<0)return;const[removed]=S.assets.splice(index,1);renderAssets();renderHealth();renderNetWorth();try{await write('assets',{method:'DELETE',query:`id=eq.${id}&telegram_id=eq.${user.id}`});toast('Актив удалён')}catch(err){S.assets.splice(index,0,removed);renderAssets();renderHealth();renderNetWorth();toast('Не удалось удалить актив')}}
const matchRule=text=>{const value=String(text||'').toLowerCase();return S.rules.find(r=>r.is_active&&value.includes(String(r.pattern).toLowerCase()))};
async function saveRule(e){e.preventDefault();const form=e.target,button=form.querySelector('[type="submit"]'),pattern=$('#rule-pattern').value.trim(),categoryId=$('#rule-category').value;if(!pattern)return toast('Введите текст для правила');if(!categoryId)return toast('Выберите категорию');if(S.rules.some(r=>r.pattern.toLowerCase()===pattern.toLowerCase()))return toast('Такое правило уже существует');button.disabled=true;button.textContent='Добавляю…';try{const rows=await write('category_rules',{body:{telegram_id:user.id,pattern,category_id:categoryId,match_field:'text'}}),category=S.categories.find(c=>c.id===categoryId),row=rows[0];if(!row)throw Error('Supabase не вернул созданное правило');S.rules.push({...row,categories:category?{name:category.name,emoji:category.emoji}:null});renderRules();form.reset();toast('Правило добавлено')}catch(err){console.error(err);toast(`Не удалось добавить: ${String(err.message).slice(0,70)}`)}finally{button.disabled=false;button.textContent='Добавить правило'}}
async function deleteRule(id){const index=S.rules.findIndex(r=>r.id===id);if(index<0)return;const [removed]=S.rules.splice(index,1);renderRules();try{await write('category_rules',{method:'DELETE',query:`id=eq.${id}&telegram_id=eq.${user.id}`});toast('Правило удалено')}catch(err){S.rules.splice(index,0,removed);renderRules();console.error(err);toast('Не удалось удалить правило')}}
async function saveRefund(e){e.preventDefault();const form=e.target,button=form.querySelector('[type="submit"]'),original=S.transactions.find(t=>t.id===$('#refund-original').value);if(!original)return toast('Исходная операция не найдена');const amount=Number($('#refund-amount').value);if(amount>Number(original.amount))return toast('Возврат не может быть больше покупки');button.disabled=true;button.textContent='Сохраняю…';try{const rows=await write('transactions',{body:{telegram_id:user.id,account_id:original.account_id,category_id:original.category_id,type:'income',amount,currency:original.currency||accountCurrency(original.account_id),fx_rate_to_rub:original.fx_rate_to_rub||toRub(original.currency||accountCurrency(original.account_id)),merchant:original.merchant,tags:original.tags||[],note:$('#refund-note').value.trim()||'Возврат',transaction_date:new Date(`${$('#refund-date').value}T12:00:00`).toISOString(),original_transaction_id:original.id,is_refund:true,source:'refund'}});const row=rows[0];if(!row)throw Error('Возврат не создан');S.transactions.unshift({...row,categories:original.categories});hide('refund-sheet');form.reset();A.render();renderAll();toast('Возврат привязан к покупке')}catch(err){console.error(err);toast('Не удалось сохранить возврат')}finally{button.disabled=false;button.textContent='Сохранить возврат'}}
function openRefund(id){const t=S.transactions.find(x=>x.id===id);if(!t)return;$('#refund-original').value=t.id;$('#refund-amount').value=t.amount;$('#refund-amount').max=t.amount;$('#refund-date').value=new Date().toISOString().slice(0,10);$('#refund-source').textContent=`${t.categories?.name||t.note||'Покупка'} · ${fmt(t.amount,t.currency||accountCurrency(t.account_id))}`;sheet('refund-sheet')}
function splitOptions(){return S.categories.filter(c=>c.type==='expense').map(c=>`<option value="${c.id}">${esc(c.emoji||'')} ${esc(c.name)}</option>`).join('')}
function addSplitRow(value=''){const row=document.createElement('div');row.className='split-row';row.innerHTML=`<select aria-label="Категория части">${splitOptions()}</select><input aria-label="Сумма части" type="number" min="0.01" step="any" value="${value}"><button type="button" aria-label="Удалить часть">×</button>`;row.querySelector('button').onclick=()=>{row.remove();updateSplitTotal()};row.querySelector('input').oninput=updateSplitTotal;$('#split-rows').append(row);updateSplitTotal()}
function updateSplitTotal(){const sum=$$('#split-rows input').reduce((s,x)=>s+Number(x.value||0),0),cur=accountCurrency($('#transaction-account').value);setText('split-total',`Распределено: ${fmt(sum,cur)}`)}

function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const rows=lines.map(line=>{let q=false,v='',out=[];for(const ch of line){if(ch==='"')q=!q;else if(ch===sep&&!q){out.push(v.trim());v=''}else v+=ch}out.push(v.trim());return out});const header=rows.shift().map(x=>x.toLowerCase()),find=(r,names)=>{const i=header.findIndex(h=>names.some(n=>h.includes(n)));return i>=0?r[i]:''};return rows.map((r,i)=>{const raw=find(r,['сумм','amount','операц','приход','расход']),amount=Number(String(raw).replace(/\s/g,'').replace(',','.').replace(/[^\d.-]/g,'')),desc=find(r,['опис','назнач','детал','merchant','контраг','катег'])||`Импорт ${i+1}`,dt=find(r,['дата','date']);return{amount:Math.abs(amount),type:amount<0?'expense':'income',note:desc,merchant:detectMerchant(desc),date:normalizeDate(dt),external_id:`csv-${dt}-${amount}-${desc}`}}).filter(x=>x.amount>0)}
const normalizeDate=v=>{const m=String(v).match(/(\d{1,4})[.\/-](\d{1,2})[.\/-](\d{1,4})/);if(!m)return new Date().toISOString().slice(0,10);return m[1].length===4?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`};
const detectMerchant=s=>{const x=String(s),known=['Яндекс','Ozon','Озон','Wildberries','WB','Spotify','Netflix','Магнит','Пятёрочка','Лента'];return known.find(k=>x.toLowerCase().includes(k.toLowerCase()))||x.split(/[ ,.;]/).filter(Boolean).slice(0,3).join(' ')};
async function parsePDF(file){const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent();text+=c.items.map(x=>x.str).join(' ')+'\n'}const rows=[];for(const line of text.split(/\n/)){const dm=line.match(/(\d{2}[.\/-]\d{2}[.\/-]\d{2,4})/),am=[...line.matchAll(/-?\s*\d[\d\s]*[,.]\d{2}/g)].pop();if(dm&&am){const n=Number(am[0].replace(/\s/g,'').replace(',','.'));rows.push({amount:Math.abs(n),type:n<0?'expense':'income',note:line.slice(0,160),merchant:detectMerchant(line),date:normalizeDate(dm[1]),external_id:`pdf-${dm[1]}-${n}-${line.slice(0,40)}`})}}return rows}
async function selectStatement(e){const file=e.target.files[0];if(!file)return;try{$('#import-preview').innerHTML='<div class="empty-state">Разбираю файл…</div>';importRows=file.name.toLowerCase().endsWith('.pdf')?await parsePDF(file):parseCSV(await file.text());$('#import-preview').innerHTML=importRows.length?importRows.slice(0,50).map(x=>`<article class="suite-row"><div><strong>${esc(x.merchant||x.note)}</strong><span>${x.date}</span></div><strong class="${x.type==='income'?'positive':'negative'}">${x.type==='income'?'+':'−'} ${fmt(x.amount,accountCurrency($('#import-account').value))}</strong></article>`).join(''):'<div class="empty-state">Операции не распознаны. Попробуйте CSV.</div>';$('#import-confirm').disabled=!importRows.length}catch(err){console.error(err);toast('Не удалось разобрать файл')}}
async function confirmImport(){const button=$('#import-confirm'),account=$('#import-account').value,currency=accountCurrency(account),fallback=S.categories.find(c=>c.type==='expense'),income=S.categories.find(c=>c.type==='income');const body=importRows.map(x=>{const rule=matchRule(`${x.merchant} ${x.note}`);return{telegram_id:user.id,account_id:account,category_id:(x.type==='income'?income:(rule?S.categories.find(c=>c.id===rule.category_id):fallback))?.id,type:x.type,amount:x.amount,currency,fx_rate_to_rub:toRub(currency),merchant:x.merchant,note:x.note,transaction_date:new Date(`${x.date}T12:00:00`).toISOString(),source:'import',external_id:x.external_id}});button.disabled=true;button.textContent='Импортирую…';try{const rows=await write('transactions',{body});rows.forEach(t=>{const c=S.categories.find(x=>x.id===t.category_id);S.transactions.push({...t,categories:c?{name:c.name,emoji:c.emoji}:null})});S.transactions.sort((a,b)=>new Date(b.transaction_date)-new Date(a.transaction_date));importRows=[];hide('import-sheet');A.render();renderAll();toast(`Импортировано: ${rows.length}`)}catch(e){console.error(e);toast('Ошибка импорта или повторный файл')}finally{button.disabled=false;button.textContent='Импортировать операции'}}

function startVoice(){const Rec=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Rec)return toast('Голосовой ввод не поддерживается этим браузером');if(!user)return toast('Откройте приложение внутри Telegram');const rec=new Rec();rec.lang='ru-RU';rec.interimResults=false;$('#voice-input').classList.add('listening');rec.onend=()=>$('#voice-input').classList.remove('listening');rec.onerror=()=>toast('Не удалось распознать голос');rec.onresult=async e=>{const text=e.results[0][0].transcript,m=text.match(/(\d[\d\s]*(?:[,.]\d+)?)/);if(!m)return toast('Не услышал сумму');const amount=Number(m[1].replace(/\s/g,'').replace(',','.')),note=text.replace(m[0],'').replace(/^(потратил|потратила|расход|заплатил|заплатила)\s*/i,'').trim()||'Голосовой расход',rule=matchRule(note),category=(rule&&S.categories.find(c=>c.id===rule.category_id))||S.categories.find(c=>c.type==='expense'&&/бенз|топлив|такси|транспорт/i.test(note)&&c.name==='Транспорт')||S.categories.find(c=>c.type==='expense'),account=S.accounts[0],d=new Date().toISOString();try{const rows=await write('transactions',{body:{telegram_id:user.id,account_id:account.id,category_id:category?.id,type:'expense',amount,currency:account.currency,fx_rate_to_rub:toRub(account.currency),merchant:detectMerchant(note),note,transaction_date:d,source:'voice'}}),row=rows[0];if(!row)throw Error();S.transactions.unshift({...row,categories:category?{name:category.name,emoji:category.emoji}:null});A.render();renderAll();toast(`Записал расход: ${fmt(amount,account.currency)}`)}catch(err){console.error(err);toast('Не удалось сохранить голосовой расход')}};rec.start()}

function reportData(period){const now=new Date(),start=period==='year'?new Date(now.getFullYear(),0,1):new Date(now.getFullYear(),now.getMonth(),1),tx=S.transactions.filter(t=>new Date(t.transaction_date)>=start),inc=tx.filter(t=>t.type==='income').reduce((s,t)=>s+historicRub(t),0),exp=tx.filter(t=>t.type==='expense').reduce((s,t)=>s+historicRub(t),0),cats={};tx.filter(t=>t.type==='expense').forEach(t=>{const k=t.categories?.name||'Другое';cats[k]=(cats[k]||0)+historicRub(t)});return{start,now,tx,inc,exp,cats}}
async function downloadReport(){if(!window.jspdf)return toast('Модуль PDF ещё загружается');const{jsPDF}=window.jspdf,d=reportData($('#report-period').value),doc=new jsPDF(),money=n=>`${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n)} RUB`;doc.setFillColor(14,16,23);doc.rect(0,0,210,297,'F');doc.setTextColor(245,247,251);doc.setFontSize(22);doc.text('Finance report',16,22);doc.setFontSize(10);doc.setTextColor(150,155,168);doc.text(`${d.start.toLocaleDateString('ru-RU')} - ${d.now.toLocaleDateString('ru-RU')}`,16,30);doc.setTextColor(245,247,251);doc.setFontSize(14);doc.text(`Income: ${money(d.inc)}`,16,48);doc.text(`Expenses: ${money(d.exp)}`,16,59);doc.text(`Net: ${money(d.inc-d.exp)}`,16,70);doc.setFontSize(13);doc.text('Expense categories',16,90);let y=101;doc.setFontSize(10);for(const[k,v]of Object.entries(d.cats).sort((a,b)=>b[1]-a[1])){doc.text(k.replace(/[^\x20-\x7EА-Яа-яЁё]/g,''),16,y);doc.text(money(v),194,y,{align:'right'});y+=9;if(y>270){doc.addPage();doc.setFillColor(14,16,23);doc.rect(0,0,210,297,'F');doc.setTextColor(245,247,251);y=20}}doc.save(`finance-report-${d.now.toISOString().slice(0,10)}.pdf`);toast('PDF-отчёт готов')}

$('#open-debts').onclick=()=>sheet('debts-sheet');$('#open-assets').onclick=()=>sheet('assets-sheet');$('#open-health').onclick=()=>sheet('health-sheet');$('#open-import').onclick=()=>{sheet('import-sheet');$('#import-account').innerHTML=S.accounts.map(a=>`<option value="${a.id}">${esc(a.name)} · ${a.currency}</option>`).join('')};$('#open-report').onclick=()=>sheet('report-sheet');$('#open-rules').onclick=()=>{renderRules();sheet('rules-sheet')};$('#debt-form').onsubmit=saveDebt;$('#asset-form').onsubmit=saveAsset;$('#rule-form').onsubmit=saveRule;$('#refund-form').onsubmit=saveRefund;$('#statement-file').onchange=selectStatement;$('#import-confirm').onclick=confirmImport;$('#voice-input').onclick=startVoice;$('#download-report').onclick=downloadReport;$('#toggle-split').onclick=()=>{const box=$('#split-editor');box.hidden=!box.hidden;if(!box.hidden&&!$('#split-rows').children.length){addSplitRow();addSplitRow()}};$('#add-split-row').onclick=()=>addSplitRow();document.addEventListener('click',e=>{const refund=e.target.closest('[data-refund-tx]'),rule=e.target.closest('[data-delete-rule]');if(refund)openRefund(refund.dataset.refundTx);if(rule)deleteRule(rule.dataset.deleteRule)});['transaction-merchant','transaction-note'].forEach(id=>$('#'+id).addEventListener('input',()=>{const r=matchRule(`${$('#transaction-merchant').value} ${$('#transaction-note').value}`);if(r&&S.formType==='expense')$('#transaction-category').value=r.category_id}));
renderAll();
